### ISSUE TITLE
Example for Customized built-in elements

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [gbj/custom-elements#1]
Hi,

Is it possible to have a complete example of the Customized built-in elements ?  
I'm getting: `TypeError: Class extends value undefined is not a constructor or null`, and I don't understand where I have wrong ...

Thanks
Marc-Antoine

**Comment by gbj** [comment]
There’s an example in the docs [here](https://docs.rs/custom-elements/0.2.0/custom_elements/trait.CustomElement.html#method.superclass)

If that doesn’t work could you share an example of what you’re doing that’s not working?

See the browser compatibility table linked from the docs as well.
