### ISSUE TITLE
Remove or make console.log optional

### ISSUE THREAD

**Issue by lukethacoder** [gbj/custom-elements#2]
https://github.com/gbj/custom-elements/blob/50fab80c9b9863dfa4429449ba00308f29a3cfe7/src/make_custom_element.js#L9

This line is handy when building your web components, but once you're done with build, this only bloats up the browser console.

Can we remove or at least put it behind a debug flag of some sort?

**Comment by gbj** [comment]
Of course, it should be removed — I suspect I just added it and lost track of it at some point, and this crate is not widely used (including by me) so nobody noticed it. If it was useful to you during debugging, I'm open to a PR that allows it to be toggled on/off.
